# Generated by Django 3.0.7 on 2021-03-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0004_auto_20200906_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
    ]
