# Generated by Django 3.0.7 on 2021-03-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0006_candidates_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='is_recruiter',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='user',
        ),
    ]
